import { createContext, useContext, useState, useEffect } from 'react';

// Translation strings
const translations = {
  de: {
    // Navigation
    dashboard: 'Dashboard',
    incidents: 'Vorfälle',
    buildings: 'Gebäude',
    properties: 'Objekte',
    tenants: 'Mieter',
    serviceProviders: 'Dienstleister',
    reports: 'Berichte',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    employees: 'Mitarbeiter',
    pmCompanies: 'PM Unternehmen',
    yourProducts: 'Ihre Produkte',
    current: 'Aktuell',

    // Sidebar sections
    overview: 'Übersicht',
    management: 'Verwaltung',
    operations: 'Betrieb',
    pmWorkspace: 'PM ARBEITSBEREICH',
    backToFmGlobal: '← Zurück zu FM Global',
    dataManagement: 'Datenverwaltung',
    quickAccess: 'Schnellzugriff',
    selectPmCompany: 'PM Unternehmen auswählen...',
    adminPanel: 'Admin Panel',

    // Settings tabs
    company: 'Unternehmen',
    profile: 'Profil',
    security: 'Sicherheit',
    billing: 'Abrechnung',
    users: 'Benutzer',

    // Settings - Company
    companyInformation: 'Unternehmensinformationen',
    companyName: 'Firmenname',
    inboundPhoneNumber: 'Eingehende Telefonnummer',
    phoneHint: 'Die Telefonnummer, die Mieter für Notfälle außerhalb der Geschäftszeiten anrufen',
    fmOncallPhone: 'FM-Bereitschaftstelefon',
    fmOncallName: 'FM-Bereitschaftsname',
    ownerEmail: 'Inhaber E-Mail',
    aiConfidenceThreshold: 'KI-Vertrauensschwelle',
    moreEscalations: 'Mehr Eskalationen',
    fewerEscalations: 'Weniger Eskalationen',
    accountStatus: 'Kontostatus',
    status: 'Status',
    created: 'Erstellt',
    saveChanges: 'Änderungen speichern',
    saving: 'Speichern...',

    // Settings - Profile
    yourProfile: 'Ihr Profil',
    name: 'Name',
    email: 'E-Mail',
    role: 'Rolle',
    admin: 'Admin',
    staff: 'Mitarbeiter',
    updateProfile: 'Profil aktualisieren',

    // Settings - Security
    changePassword: 'Passwort ändern',
    currentPassword: 'Aktuelles Passwort',
    newPassword: 'Neues Passwort',
    confirmPassword: 'Passwort bestätigen',
    minCharacters: 'Mindestens 8 Zeichen',
    reenterPassword: 'Passwort erneut eingeben',
    changing: 'Ändern...',

    // Settings - Users
    teamMembers: 'Teammitglieder',
    addUser: 'Benutzer hinzufügen',
    addTeamMember: 'Neues Teammitglied hinzufügen',
    user: 'Benutzer',
    actions: 'Aktionen',
    noUsersYet: 'Noch keine Benutzer',
    addTeamMembers: 'Fügen Sie Teammitglieder hinzu, um das System zu verwalten.',
    userInformation: 'Benutzerinformationen',
    fullName: 'Vollständiger Name',
    password: 'Passwort',
    required: 'Erforderlich',
    adminAccess: 'Admin-Zugriff',
    canManageUsersSettings: 'Kann Benutzer und Einstellungen verwalten',
    cancel: 'Abbrechen',
    createUser: 'Benutzer erstellen',
    creating: 'Erstellen...',

    // Settings - Billing
    loadingBilling: 'Lade Abrechnungsinformationen...',
    daysLeftInTrial: 'Tage in der Testphase',
    subscribeTooContinue: 'Abonnieren Sie, um After Hour Dispatch nach Ablauf Ihrer Testphase weiter zu nutzen',
    currentPlan: 'Aktueller Plan',
    activeSubscription: 'Aktives Abonnement',
    noActiveSubscription: 'Kein aktives Abonnement',
    active: 'Aktiv',
    pastDue: 'Überfällig',
    trial: 'Testphase',
    inactive: 'Inaktiv',
    endsOn: 'Endet am',
    renewsOn: 'Verlängert am',
    manage: 'Verwalten',
    chooseYourPlan: 'Wählen Sie Ihren Plan',
    selectPlanDescription: 'Wählen Sie den Plan, der am besten zu Ihnen passt.',
    annualDiscount: '2 Monate gratis bei Jahresvertrag (≈17% Rabatt)',
    onlinePaymentsComingSoon: 'Online-Zahlungen demnächst verfügbar. Kontaktieren Sie uns, um zu abonnieren.',
    mostPopular: 'Am beliebtesten',
    onRequest: 'Auf Anfrage',
    upTo: 'bis zu',
    callsPerMonth: 'Anrufe/Monat',
    setup: 'Einrichtung',
    loading: 'Lädt...',
    contactSales: 'Kontakt aufnehmen',
    getStarted: 'Jetzt starten',
    comingSoon: 'Demnächst verfügbar',
    billingHistory: 'Rechnungsverlauf',
    date: 'Datum',
    amount: 'Betrag',
    invoice: 'Rechnung',
    paid: 'Bezahlt',
    open: 'Offen',
    view: 'Ansehen',

    // Messages
    companySettingsSaved: 'Unternehmenseinstellungen erfolgreich gespeichert',
    failedToSaveCompanySettings: 'Fehler beim Speichern der Unternehmenseinstellungen',
    profileUpdated: 'Profil erfolgreich aktualisiert',
    failedToUpdateProfile: 'Fehler beim Aktualisieren des Profils',
    passwordsDoNotMatch: 'Neue Passwörter stimmen nicht überein',
    passwordTooShort: 'Passwort muss mindestens 8 Zeichen lang sein',
    passwordChanged: 'Passwort erfolgreich geändert',
    failedToChangePassword: 'Fehler beim Ändern des Passworts',
    emailPasswordRequired: 'E-Mail und Passwort sind erforderlich',
    userCreated: 'Benutzer erfolgreich erstellt',
    failedToCreateUser: 'Fehler beim Erstellen des Benutzers',
    userDeleted: 'Benutzer erfolgreich gelöscht',
    failedToDeleteUser: 'Fehler beim Löschen des Benutzers',
    failedToStartCheckout: 'Fehler beim Starten des Checkouts',
    failedToOpenBillingPortal: 'Fehler beim Öffnen des Abrechnungsportals',
    failedToLoadSettings: 'Fehler beim Laden der Einstellungen',
    loadingSettings: 'Lade Einstellungen...',
    confirmDeleteUser: 'Sind Sie sicher, dass Sie diesen Benutzer löschen möchten?',

    // Page headers
    manageSettings: 'Verwalten Sie Ihre Unternehmens- und Kontoeinstellungen',

    // Language
    language: 'Sprache',
    german: 'Deutsch',
    english: 'English',

    // Dashboard
    afterHoursOverview: 'After-Hours Service Übersicht',
    dark: 'Dunkel',
    light: 'Hell',
    callsTonight: 'Anrufe heute Nacht',
    openIncidents: 'Offene Vorfälle',
    activePMs: 'Aktive PMs',
    totalProperties: 'Objekte gesamt',
    totalActiveCompanies: 'Aktive Unternehmen gesamt',
    acrossAllPMs: 'Über alle PMs',
    callsToday: 'Anrufe heute',
    requiresAttention: 'Erfordert Aufmerksamkeit',
    allClear: 'Alles in Ordnung',
    thisWeek: 'Diese Woche',
    thisMonth: 'Diesen Monat',
    emergencies: 'Notfälle',
    missingReports: 'Fehlende Berichte',
    calls: 'Anrufe',
    callActivityLast7Days: 'Anrufaktivität (Letzte 7 Tage)',
    resolved: 'Erledigt',
    responseRate: 'Antwortrate',
    completed: 'Abgeschlossen',
    avgResponse: 'Durchschn. Antwort',
    manageCompanies: 'Unternehmen verwalten',
    servicePhone: 'Service-Telefon',
    lastIncident: 'Letzter Vorfall',
    action: 'Aktion',
    enter: 'Öffnen',
    noPmCompaniesYet: 'Noch keine PM Unternehmen',
    addFirstPmCompanyDescription: 'Fügen Sie Ihr erstes PM Unternehmen hinzu, um deren Objekte und Mieter zu verwalten.',
    addPmCompany: 'PM Unternehmen hinzufügen',
    gettingStarted: 'Erste Schritte',
    gettingStartedDescription: 'Wählen Sie ein PM Unternehmen aus der Tabelle oben, um dessen Arbeitsbereich zu betreten. In einem PM-Arbeitsbereich können Sie Objekte, Mieter, Dienstleister verwalten und PM-spezifische Vorfälle und Berichte einsehen.',
    loadingDashboard: 'Lade Dashboard...',
    mon: 'Mo',
    tue: 'Di',
    wed: 'Mi',
    thu: 'Do',
    fri: 'Fr',
    sat: 'Sa',
    sun: 'So',

    // Onboarding Checklist
    completeYourSetup: 'Vervollständigen Sie Ihre Einrichtung',
    stepsCompleted: '{0} von {1} Schritten abgeschlossen',
    tour: 'Tour',
    dismissChecklist: 'Checkliste ausblenden',
    done: 'Erledigt',
    onboardingWelcomeTitle: 'Willkommen bei After Hour Dispatch',
    onboardingWelcomeDesc: 'Lassen Sie uns Sie einrichten',
    onboardingAddPmTitle: 'Fügen Sie Ihren ersten Kunden hinzu',
    onboardingAddPmDesc: 'Fügen Sie ein Hausverwaltungsunternehmen hinzu, das Sie betreuen',
    onboardingAddSpTitle: 'Dienstleister hinzufügen',
    onboardingAddSpDesc: 'Fügen Sie Auftragnehmer hinzu (Klempner, Elektriker usw.)',
    onboardingAddEmployeeTitle: 'Teammitglieder hinzufügen',
    onboardingAddEmployeeDesc: 'Fügen Sie Mitarbeiter hinzu, die Bereitschaftsdienst haben können',
    onboardingScheduleTitle: 'Bereitschaftsplan einrichten',
    onboardingScheduleDesc: 'Legen Sie fest, wer After-Hours-Anrufe bearbeitet',
    onboardingEmergencyLineTitle: 'Notfall-Rufnummer einrichten',
    onboardingEmergencyLineDesc: 'Eigene Nummer erhalten oder bestehende weiterleiten – dauert 2 Minuten',

    // Emergency Line (Telephony)
    emergencyLine: 'Notfall-Rufnummer',
    emergencyLineIntro: 'Die Telefonnummer, unter der Ihre Mieter außerhalb der Geschäftszeiten Notfälle melden. Pro Kunde einrichten.',
    emergencyLineNotSetUp: 'Ihre Notfall-Rufnummer ist noch nicht eingerichtet.',
    emergencyLineNotSetUpDesc: 'Mieter können After Hour erst erreichen, wenn dieser Schritt abgeschlossen ist.',
    finishSetup: 'Einrichtung abschließen',
    getDedicatedNumber: 'Eigene Rufnummer erhalten',
    useMyOwnNumber: 'Eigene Nummer weiterleiten (kostenlos)',
    yourEmergencyNumber: 'Ihre Notfall-Rufnummer',
    yourPublishedNumber: 'Die Nummer, die Ihre Mieter derzeit anrufen',
    yourNumber: 'Ihre Nummer',
    enterYourNumber: 'Bitte geben Sie zuerst Ihre veröffentlichte Nummer ein',
    forwardsTo: 'Weiterleitung an',
    forwardYourLineTo: 'Richten Sie eine bedingte Rufumleitung (bei Nichtannahme) von Ihrer veröffentlichten Nummer ein an',
    carrierInstructions: 'Anleitung nach Anbieter',
    perMonth: 'Monat',
    lineIsLive: 'Ihre Notfall-Rufnummer ist aktiv.',
    testMyLine: 'Rufnummer testen',
    iHeardIt: 'Ich habe den Assistenten gehört',
    checkNumberConfig: 'Nummer konfiguriert',
    checkRouting: 'Weiterleitung geprüft',
    releaseThisNumber: 'Diese Rufnummer freigeben',
    confirmReleaseNumber: 'Diese Rufnummer freigeben? Mieter können After Hour darüber nicht mehr erreichen.',
    provisioningUnavailable: 'Die Nummerneinrichtung ist vorübergehend nicht verfügbar – bitte kontaktieren Sie den Support.',
    addClientFirst: 'Fügen Sie zuerst einen Kunden (Hausverwaltung) hinzu, dann richten Sie hier die Notfall-Rufnummer ein.',
    lineStatusActive: 'Aktiv',
    lineStatusProvisioning: 'Wird eingerichtet',
    lineStatusForwardingPending: 'Weiterleitung ausstehend',
    lineStatusPortPending: 'Portierung ausstehend',
    lineStatusUnassigned: 'Nicht eingerichtet',
    lineStatusReleased: 'Freigegeben',

    // Welcome Modal
    welcomeModalTitle: 'Willkommen bei After Hour Dispatch!',
    welcomeModalSubtitle: 'Ihr Notfall-Dispatch-System außerhalb der Geschäftszeiten ist bereit',
    welcomeModalBody: 'Richten wir Ihr Konto ein, damit Sie mit der Verwaltung von After-Hours-Notfällen für Ihre Kunden beginnen können.',
    takeQuickTour: 'Kurze Tour starten',
    skipTourShowChecklist: 'Tour überspringen, Checkliste anzeigen',
    whatYoullSetUp: 'Was Sie einrichten werden:',
    welcomeSetupPm: 'PM Unternehmen hinzufügen (Ihre Kunden)',
    welcomeSetupSp: 'Dienstleister hinzufügen (Klempner, Elektriker)',
    welcomeSetupTeam: 'Teammitglieder einrichten',
    welcomeSetupSchedule: 'Bereitschaftspläne konfigurieren',

    // Guided Tour
    tourSidebarTitle: 'Navigation',
    tourSidebarContent: 'Nutzen Sie die Seitenleiste, um zwischen den Bereichen zu navigieren. Das Dashboard zeigt Ihre Übersicht, und Sie können PM Unternehmen, Dienstleister und mehr verwalten.',
    tourPmCompaniesTitle: 'PM Unternehmen',
    tourPmCompaniesContent: 'Beginnen Sie hier! Fügen Sie die Hausverwaltungsunternehmen hinzu, für die Sie den After-Hours-Service bereitstellen.',
    tourServiceProvidersTitle: 'Dienstleister',
    tourServiceProvidersContent: 'Fügen Sie Ihre Auftragnehmer hinzu - Klempner, Elektriker, Schlosser - die Notfallanrufe bearbeiten.',
    tourEmployeesTitle: 'Ihr Team',
    tourEmployeesContent: 'Fügen Sie Teammitglieder hinzu, die für Bereitschaftsschichten eingeteilt werden können.',
    tourSchedulesTitle: 'Bereitschaftspläne',
    tourSchedulesContent: 'Legen Sie fest, wer Anrufe außerhalb der Geschäftszeiten bearbeitet. Sie können wiederkehrende Pläne oder einmalige Zuweisungen erstellen.',
    tourIncidentsTitle: 'Vorfälle',
    tourIncidentsContent: 'Alle eingehenden Anrufe und Notfälle erscheinen hier. Sie sehen Echtzeit-Updates, sobald Anrufe eingehen.',
    tourStepOf: 'Schritt {0} von {1}',
    tourFinish: 'Fertig',
    tourNext: 'Weiter',
    tourPrevious: 'Zurück',
    tourSkip: 'Tour überspringen',

    // Login/Signup
    fmAdminPortal: 'FM Admin Portal',
    emailAddress: 'E-Mail-Adresse',
    enterYourEmail: 'Geben Sie Ihre E-Mail-Adresse ein',
    enterYourPassword: 'Geben Sie Ihr Passwort ein',
    forgotPassword: 'Passwort vergessen?',
    signingIn: 'Anmelden...',
    signIn: 'Anmelden',
    dontHaveAccount: 'Sie haben noch kein Konto?',
    startFreeTrial: 'Kostenlos testen',
    afterHoursEmergencyDispatch: 'Notfall-Dispatch-System außerhalb der Geschäftszeiten',
    loginFailed: 'Anmeldung fehlgeschlagen',

    // Signup
    startYourFreeTrial: 'Starten Sie Ihre kostenlose Testphase',
    companyNameRequired: 'Firmenname ist erforderlich',
    companyPhoneRequired: 'Firmen-Telefonnummer ist erforderlich',
    yourNameRequired: 'Ihr Name ist erforderlich',
    emailRequired: 'E-Mail ist erforderlich',
    invalidEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
    passwordRequired: 'Passwort ist erforderlich',
    passwordMinLength: 'Passwort muss mindestens 8 Zeichen haben',
    passwordsMustMatch: 'Passwörter stimmen nicht überein',
    yourFmCompanyName: 'Ihr FM-Firmenname',
    companyPhoneNumber: 'Firmen-Telefonnummer',
    mainCompanyContact: 'Ihre Hauptkontaktnummer',
    onCallPhoneOptional: 'Bereitschaftstelefon (Optional)',
    escalationPhoneNumber: 'Eskalations-Telefonnummer',
    whereUrgentEscalations: 'Wohin dringende Eskalationen gesendet werden (Standard: Firmentelefon)',
    continue: 'Weiter',
    alreadyHaveAccount: 'Sie haben bereits ein Konto?',
    yourFullName: 'Ihr vollständiger Name',
    atLeast8Characters: 'Mindestens 8 Zeichen',
    confirmYourPassword: 'Passwort bestätigen',
    freeTrialDays: '14 Tage kostenlose Testphase',
    noCreditCardRequired: 'Keine Kreditkarte erforderlich. Voller Zugang zu allen Funktionen.',
    back: 'Zurück',
    creatingAccount: 'Konto wird erstellt...',
    createAccount: 'Konto erstellen',
    agreeToTerms: 'Mit der Erstellung eines Kontos stimmen Sie unseren Nutzungsbedingungen und Datenschutzrichtlinien zu',
    agreeToTermsCheckbox: 'Ich stimme den',
    termsOfService: 'Nutzungsbedingungen',
    and: 'und',
    privacyPolicy: 'Datenschutzrichtlinien',
    mustAcceptTerms: 'Sie müssen den Nutzungsbedingungen zustimmen, um fortzufahren',
    account: 'Konto',
    verify: 'Bestätigen',
    weWillSendCode: 'Wir senden Ihnen einen Bestätigungscode',
    sendCode: 'Code senden',
    verifyCode: 'Code bestätigen',
    verifying: 'Wird überprüft...',
    codeSentTo: 'Code gesendet an',
    didntReceiveCode: 'Keinen Code erhalten?',
    resendIn: 'Erneut senden in',
    resendCode: 'Code erneut senden',
    changeEmail: 'E-Mail ändern',

    // Status Banners
    trialExpired: 'Ihre Testphase ist abgelaufen.',
    daysLeftTrial: 'Tage verbleibend in Ihrer kostenlosen Testphase.',
    dayLeftTrial: 'Tag verbleibend in Ihrer kostenlosen Testphase.',
    subscribeNowToContinue: 'Abonnieren Sie jetzt, um After Hour Dispatch weiter zu nutzen.',
    upgradeToKeepData: 'Upgraden Sie, um Ihre Daten zu behalten und nach der Testphase weiterzuarbeiten.',
    subscribeNow: 'Jetzt abonnieren',
    upgrade: 'Upgraden',
    verifyEmailAddress: 'Bitte bestätigen Sie Ihre E-Mail-Adresse',
    toReceiveNotifications: 'um wichtige Benachrichtigungen zu erhalten.',
    verificationEmailSent: 'Bestätigungs-E-Mail gesendet!',
    sending: 'Senden...',
    resendEmail: 'E-Mail erneut senden',
    dismiss: 'Schließen',

    // Buildings Page
    loadingBuildings: 'Lade Gebäude...',
    managePropertiesAcrossPM: 'Verwalten Sie Objekte über alle PM Unternehmen',
    totalBuildings: 'Gebäude gesamt',
    totalTenants: 'Mieter gesamt',
    buildingsByPmCompany: 'Gebäude nach PM Unternehmen',
    selectCompanyToManage: 'Wählen Sie ein Unternehmen aus, um seine Gebäude zu verwalten',
    noPmCompaniesYetBuildings: 'Noch keine PM Unternehmen',
    addFirstPmToManageBuildings: 'Fügen Sie Ihr erstes PM Unternehmen hinzu, um Gebäude zu verwalten.',

    // Tenants Page
    loadingTenants: 'Lade Mieter...',
    manageTenantsAcrossPM: 'Verwalten Sie Mieter über alle PM Unternehmen',
    tenantsByPmCompany: 'Mieter nach PM Unternehmen',
    selectCompanyToManageTenants: 'Wählen Sie ein Unternehmen aus, um seine Mieter zu verwalten',
    addFirstPmToManageTenants: 'Fügen Sie Ihr erstes PM Unternehmen hinzu, um Mieter zu verwalten.',

    // Service Providers Page
    loadingServiceProviders: 'Lade Dienstleister...',
    contractorsAndVendors: 'Auftragnehmer und Lieferanten für Notfallreparaturen',
    totalProviders: 'Dienstleister gesamt',
    paused: 'Pausiert',
    allPmCompanies: 'Alle PM Unternehmen',
    allTrades: 'Alle Gewerke',
    addProvider: 'Dienstleister hinzufügen',
    noServiceProviders: 'Keine Dienstleister',
    addContractorsDescription: 'Fügen Sie Auftragnehmer und Lieferanten für Notfallreparaturen hinzu.',
    trade: 'Gewerk',
    phone: 'Telefon',
    editServiceProvider: 'Dienstleister bearbeiten',
    addServiceProvider: 'Dienstleister hinzufügen',
    editing: 'Bearbeiten:',
    addContractorOrVendor: 'Auftragnehmer oder Lieferant hinzufügen',
    companyInformationSection: 'Unternehmensinformationen',
    tradeSpecialty: 'Gewerk / Fachgebiet',
    contactInformation: 'Kontaktinformationen',
    contactPerson: 'Kontaktperson',
    primaryContactName: 'Name der Hauptkontaktperson',
    availabilityGuidanceSection: 'Verfügbarkeit & Hinweise',
    usageNote: 'Hinweis für Bereitschaftsdienst',
    usageNoteHint: 'z. B. "24/7 Notdienst, ca. 30 Min." oder "Nur Geschäftszeiten, als Ausweichoption nutzen"',
    available24h: 'Rund um die Uhr verfügbar',
    availableHoursOnly: 'Nur zu bestimmten Zeiten verfügbar',
    availableFrom: 'Verfügbar ab',
    availableTo: 'Verfügbar bis',
    plumber: 'Klempner',
    electrician: 'Elektriker',
    locksmith: 'Schlosser',
    hvac: 'Heizung/Lüftung/Klima',
    general: 'Allgemein',
    other: 'Sonstiges',
    savingChanges: 'Speichern...',

    // PM Companies Page
    loadingPmCompanies: 'Lade PM Unternehmen...',
    pmCompaniesDescription: 'Hausverwaltungen, die Sie mit After-Hours-Dispatch bedienen',
    totalCompanies: 'Unternehmen gesamt',
    withServicePhone: 'Mit Service-Telefon',
    searchPlaceholder: 'Nach Name, E-Mail oder Service-Telefon suchen...',
    allCompanies: 'Alle Unternehmen',
    activeOnly: 'Nur aktive',
    inactiveOnly: 'Nur inaktive',
    withOpenIncidents: 'Mit offenen Vorfällen',
    noOpenIncidents: 'Keine offenen Vorfälle',
    showingXofY: 'Zeige {0} von {1} Unternehmen',
    afterHours: 'After-Hours',
    notSet: 'Nicht gesetzt',
    noResultsFound: 'Keine Ergebnisse gefunden',
    tryAdjustingSearch: 'Versuchen Sie, Ihre Such- oder Filterkriterien anzupassen.',
    editPmCompany: 'PM Unternehmen bearbeiten',
    addNewPmCompany: 'Neues PM Unternehmen hinzufügen',
    servicePhoneHotline: 'Service-Telefon (After-Hours-Hotline)',
    tenantsCallThis: 'Mieter rufen diese Nummer an',
    address: 'Adresse',
    streetAddress: 'Straße',
    city: 'Stadt',
    postalCode: 'Postleitzahl',
    country: 'Land',
    emailForReports: 'Für Berichte',
    phoneForEscalations: 'Für Eskalationen',
    afterHoursSettings: 'After-Hours-Einstellungen',
    afterHoursStart: 'After-Hours Beginn',
    afterHoursEnd: 'After-Hours Ende',
    aiDecisionsBelowThreshold: 'KI-Entscheidungen unter diesem Schwellenwert erfordern menschliche Überprüfung',
    additionalNotes: 'Zusätzliche Notizen',
    internalNotes: 'Interne Notizen zu diesem PM Unternehmen...',
    createCompany: 'Unternehmen erstellen',
    confirmDeletePm: 'Löschen "{0}"? Dies schlägt fehl, wenn Gebäude zugewiesen sind.',
    edit: 'Bearbeiten',
    delete: 'Löschen',

    // Employees Page
    employeesAndOnCall: 'Mitarbeiter & Bereitschaft',
    manageTeamAndRotations: 'Verwalten Sie Ihr Team und planen Sie Bereitschaftsrotationen im Voraus',
    addEmployee: 'Mitarbeiter hinzufügen',
    currentlyOnCall: 'AKTUELL IN BEREITSCHAFT',
    callsForwarded: 'Anrufe weitergeleitet',
    shiftHours: 'Schichtzeiten',
    totalEmployees: 'Mitarbeiter gesamt',
    onCallReady: 'Bereitschaftsfähig',
    weeksPlanned: 'Wochen geplant',
    weeklyRotation: 'Wöchentliche Rotation',
    teamMembersTab: 'Teammitglieder',
    callForwardingStatus: 'Anrufweiterleitungsstatus',
    forwardingTo: 'Aktiv - Weiterleitung an',
    noActiveOnCall: 'Keine aktive Bereitschaftszuweisung',
    configure: 'Konfigurieren',
    setUp: 'Einrichten',
    previous: 'Vorherige',
    next: 'Nächste',
    today: 'Heute',
    past: 'Vergangen',
    week: 'Woche',
    physicalPhone: 'PHYSISCHES TELEFON',
    notAssigned: 'Nicht zugewiesen',
    pastWeek: 'Vergangene Woche',
    clickToAssign: 'Klicken Sie, um einen Mitarbeiter zuzuweisen',
    change: 'Ändern',
    assign: 'Zuweisen',
    noOnCallEmployees: 'Keine Bereitschaftsmitarbeiter',
    addEmployeesOnCallDescription: 'Fügen Sie Mitarbeiter hinzu und markieren Sie sie als "Kann in Bereitschaft sein", um Rotationen zu planen.',
    addFirstEmployee: 'Ersten Mitarbeiter hinzufügen',
    searchEmployees: 'Mitarbeiter suchen...',
    onCall: 'BEREITSCHAFT',
    dispatcher: 'Dispatcher',
    noEmployeesYet: 'Noch keine Mitarbeiter',
    addTeamMembersDescription: 'Fügen Sie Teammitglieder hinzu, um Bereitschaftsrotationen zu verwalten.',
    editEmployee: 'Mitarbeiter bearbeiten',
    addNewEmployee: 'Neuen Mitarbeiter hinzufügen',
    updateEmployeeInfo: 'Mitarbeiterinformationen aktualisieren',
    addTeamMemberToSystem: 'Ein Teammitglied zum System hinzufügen',
    basicInformation: 'Grundlegende Informationen',
    enterFullName: 'Vollständigen Namen eingeben',
    phoneNumber: 'Telefonnummer',
    optional: 'Optional',
    settingsSection: 'Einstellungen',
    activeEmployee: 'Aktiver Mitarbeiter',
    canLoginAndAssigned: 'Mitarbeiter kann sich anmelden und Aufgaben zugewiesen bekommen',
    availableForOnCall: 'Für Bereitschaft verfügbar',
    canBeAssignedRotations: 'Kann zu wöchentlichen Bereitschaftsrotationen zugewiesen werden',
    notes: 'Notizen',
    internalNotesEmployee: 'Interne Notizen zu diesem Mitarbeiter...',
    confirmDeleteEmployee: 'Mitarbeiter "{0}" löschen? Dies entfernt auch seine Bereitschaftszuweisungen.',
    nameAndPhoneRequired: 'Name und Telefon sind erforderlich',
    failedToSaveEmployee: 'Fehler beim Speichern des Mitarbeiters:',
    failedToDeleteEmployee: 'Fehler beim Löschen des Mitarbeiters:',
    assignOnCallWeek: 'Bereitschaftswoche zuweisen',
    currentWeek: 'Aktuelle Woche',
    selectEmployee: 'Mitarbeiter auswählen',
    noEmployeesForOnCall: 'Keine Mitarbeiter für Bereitschaft verfügbar.',
    noAssignment: 'Keine Zuweisung',
    clearWeekOnCall: 'Bereitschaft dieser Woche löschen',
    phoneHandling: 'Telefonhandhabung',
    usePhysicalPhone: 'Physisches Telefon verwenden',
    employeeCarriesPhone: 'Mitarbeiter trägt diese Woche das physische After-Hours-Telefon',
    callForwardingInfo: 'Anrufweiterleitung: Anrufe werden automatisch an die persönliche Telefonnummer des Mitarbeiters weitergeleitet.',
    notesOptional: 'Notizen (Optional)',
    specialInstructionsWeek: 'Besondere Anweisungen für diese Woche...',
    immediateEffect: 'Sofortige Wirkung',
    changeWillTakeEffect: 'Diese Änderung wird sofort wirksam und aktualisiert die Anrufweiterleitung.',
    saveAssignment: 'Zuweisung speichern',
    failedToSaveAssignment: 'Fehler beim Speichern der Zuweisung:',

    // Incidents Page
    pmScopedView: 'PM-GEFILTERTE ANSICHT',
    fmGlobalView: 'FM GLOBALE ANSICHT',
    incidentsFor: 'Vorfälle:',
    allIncidentsAcrossPM: 'Alle Vorfälle über PM Unternehmen',
    allIncidents: 'Alle Vorfälle',
    openOnly: 'Nur offene',
    emergenciesOnly: 'Nur Notfälle',
    clearPmFilter: 'PM-Filter löschen',
    dateTime: 'Datum/Zeit',
    building: 'Gebäude',
    issue: 'Problem',
    severity: 'Schweregrad',
    aiConf: 'KI-Konf.',
    responsibility: 'Verantwortlichkeit',
    assignedSp: 'Zugewiesener DL',
    noIncidentsFound: 'Keine Vorfälle gefunden',
    emergency: 'NOTFALL',
    normal: 'Normal',
    reportOverdue: 'Bericht überfällig',
    spWorking: 'DL arbeitet',
    awaitingSp: 'Wartet auf DL',
    fmEscalated: 'FM eskaliert',

    // Reports Page
    reportsTitle: 'Berichte',
    pmCompanyColumn: 'PM Unternehmen',
    incidentsCount: 'Vorfälle',
    sentTo: 'Gesendet an',
    statusColumn: 'Status',
    actionsColumn: 'Aktionen',
    noReportsYet: 'Noch keine Berichte',
    sent: 'Gesendet',
    pending: 'Ausstehend',
    viewPdf: 'PDF ansehen',
    resend: 'Erneut senden',
    enterEmailToSend: 'E-Mail-Adresse eingeben, an die der Bericht gesendet werden soll:',
    reportSentSuccessfully: 'Bericht erfolgreich gesendet',

    // Forgot Password Page
    resetYourPassword: 'Passwort zurücksetzen',
    enterEmailForReset: 'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts.',
    pleaseEnterEmail: 'Bitte geben Sie Ihre E-Mail-Adresse ein',
    sendResetLink: 'Link senden',
    checkYourEmail: 'Überprüfen Sie Ihre E-Mail',
    ifAccountExists: 'Wenn ein Konto für {0} existiert, erhalten Sie in Kürze einen Link zum Zurücksetzen des Passworts.',
    didntReceiveEmail: 'E-Mail nicht erhalten? Überprüfen Sie Ihren Spam-Ordner oder versuchen Sie es erneut.',
    tryAnotherEmail: 'Andere E-Mail versuchen',
    backToSignIn: 'Zurück zur Anmeldung',

    // Reset Password Page
    setNewPassword: 'Neues Passwort festlegen',
    creatingPasswordFor: 'Neues Passwort erstellen für',
    pleaseEnterNewPassword: 'Bitte geben Sie ein neues Passwort ein',
    passwordMust8Chars: 'Passwort muss mindestens 8 Zeichen haben',
    passwordsDoNotMatchReset: 'Passwörter stimmen nicht überein',
    verifyingResetLink: 'Link wird überprüft...',
    invalidResetLink: 'Ungültiger Link',
    resetLinksExpire: 'Links zum Zurücksetzen laufen nach 1 Stunde ab. Bitte fordern Sie einen neuen an.',
    requestNewLink: 'Neuen Link anfordern',
    passwordResetComplete: 'Passwort wurde zurückgesetzt',
    passwordResetSuccess: 'Ihr Passwort wurde erfolgreich zurückgesetzt. Sie können sich jetzt mit Ihrem neuen Passwort anmelden.',
    confirmNewPassword: 'Neues Passwort bestätigen',
    resetting: 'Zurücksetzen...',
    resetPassword: 'Passwort zurücksetzen',

    // Verify Email Page
    verifyingEmail: 'E-Mail wird überprüft...',
    verificationFailed: 'Überprüfung fehlgeschlagen',
    verificationLinksExpire: 'Bestätigungslinks laufen nach 24 Stunden ab.',
    goToDashboard: 'Zum Dashboard',
    emailVerified: 'E-Mail bestätigt!',
    emailVerifiedSuccess: 'Ihre E-Mail wurde erfolgreich bestätigt. Sie haben jetzt vollen Zugriff auf alle Funktionen.',
    noVerificationToken: 'Kein Bestätigungstoken angegeben',
    pageNotFound: 'Diese Seite wurde nicht gefunden.',
    backToDashboard: 'Zurück zum Dashboard',
    // Cookie consent — was hardcoded English JSX, i.e. the first thing a
    // German visitor saw on an otherwise fully German page (QA 2026-08-09).
    cookieTitle: 'Wir verwenden Cookies',
    cookieBody: 'Wir verwenden Cookies, um Ihr Nutzungserlebnis zu verbessern, den Website-Verkehr zu analysieren und die Sicherheit zu gewährleisten. Mit Klick auf „Alle akzeptieren" stimmen Sie der Verwendung zu. Sie können Ihre Einstellungen anpassen oder nicht notwendige Cookies ablehnen.',
    cookieRejectAll: 'Alle ablehnen',
    cookieCustomize: 'Anpassen',
    cookieAcceptAll: 'Alle akzeptieren',
    cookiePreferences: 'Cookie-Einstellungen',
    cookieEssentialTitle: 'Notwendige Cookies',
    cookieEssentialDesc: 'Für den Betrieb der Website erforderlich. Können nicht deaktiviert werden.',
    cookieAnalyticsTitle: 'Analyse-Cookies',
    cookieAnalyticsDesc: 'Helfen uns zu verstehen, wie Besucher unsere Website nutzen.',
    cookieFunctionalTitle: 'Funktionale Cookies',
    cookieFunctionalDesc: 'Ermöglichen personalisierte Funktionen und speichern Ihre Einstellungen.',
    cookieSavePreferences: 'Einstellungen speichern',
    cookiePrivacyPolicy: 'Datenschutzerklärung',
  },

  en: {
    // Navigation
    dashboard: 'Dashboard',
    incidents: 'Incidents',
    buildings: 'Buildings',
    properties: 'Properties',
    tenants: 'Tenants',
    serviceProviders: 'Service Providers',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Log out',
    employees: 'Employees',
    pmCompanies: 'PM Companies',
    yourProducts: 'Your Products',
    current: 'Current',

    // Sidebar sections
    overview: 'Overview',
    management: 'Management',
    operations: 'Operations',
    pmWorkspace: 'PM WORKSPACE',
    backToFmGlobal: '← Back to FM Global',
    dataManagement: 'Data Management',
    quickAccess: 'Quick Access',
    selectPmCompany: 'Select PM Company...',
    adminPanel: 'Admin Panel',

    // Settings tabs
    company: 'Company',
    profile: 'Profile',
    security: 'Security',
    billing: 'Billing',
    users: 'Users',

    // Settings - Company
    companyInformation: 'Company Information',
    companyName: 'Company Name',
    inboundPhoneNumber: 'Inbound Phone Number',
    phoneHint: 'The phone number tenants call for after-hours emergencies',
    fmOncallPhone: 'FM On-Call Phone',
    fmOncallName: 'FM On-Call Name',
    ownerEmail: 'Owner Email',
    aiConfidenceThreshold: 'AI Confidence Threshold',
    moreEscalations: 'More Escalations',
    fewerEscalations: 'Fewer Escalations',
    accountStatus: 'Account Status',
    status: 'Status',
    created: 'Created',
    saveChanges: 'Save Changes',
    saving: 'Saving...',

    // Settings - Profile
    yourProfile: 'Your Profile',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    admin: 'Admin',
    staff: 'Staff',
    updateProfile: 'Update Profile',

    // Settings - Security
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    minCharacters: 'Minimum 8 characters',
    reenterPassword: 'Re-enter new password',
    changing: 'Changing...',

    // Settings - Users
    teamMembers: 'Team Members',
    addUser: 'Add User',
    addTeamMember: 'Add a new team member',
    user: 'User',
    actions: 'Actions',
    noUsersYet: 'No Users Yet',
    addTeamMembers: 'Add team members to help manage the system.',
    userInformation: 'User Information',
    fullName: 'Full name',
    password: 'Password',
    required: 'Required',
    adminAccess: 'Admin Access',
    canManageUsersSettings: 'Can manage users and settings',
    cancel: 'Cancel',
    createUser: 'Create User',
    creating: 'Creating...',

    // Settings - Billing
    loadingBilling: 'Loading billing information...',
    daysLeftInTrial: 'Days Left in Trial',
    subscribeTooContinue: 'Subscribe to continue using After Hour Dispatch after your trial ends',
    currentPlan: 'Current Plan',
    activeSubscription: 'Active subscription',
    noActiveSubscription: 'No active subscription',
    active: 'Active',
    pastDue: 'Past Due',
    trial: 'Trial',
    inactive: 'Inactive',
    endsOn: 'Ends on',
    renewsOn: 'Renews on',
    manage: 'Manage',
    chooseYourPlan: 'Choose Your Plan',
    selectPlanDescription: 'Select the plan that best fits your needs.',
    annualDiscount: '2 months free with annual payment (≈17% discount)',
    onlinePaymentsComingSoon: 'Online payments coming soon. Contact support to subscribe.',
    mostPopular: 'Most Popular',
    onRequest: 'On Request',
    upTo: 'up to',
    callsPerMonth: 'calls/month',
    setup: 'Setup',
    loading: 'Loading...',
    contactSales: 'Contact Sales',
    getStarted: 'Get Started',
    comingSoon: 'Coming Soon',
    billingHistory: 'Billing History',
    date: 'Date',
    amount: 'Amount',
    invoice: 'Invoice',
    paid: 'Paid',
    open: 'Open',
    view: 'View',

    // Messages
    companySettingsSaved: 'Company settings saved successfully',
    failedToSaveCompanySettings: 'Failed to save company settings',
    profileUpdated: 'Profile updated successfully',
    failedToUpdateProfile: 'Failed to update profile',
    passwordsDoNotMatch: 'New passwords do not match',
    passwordTooShort: 'Password must be at least 8 characters',
    passwordChanged: 'Password changed successfully',
    failedToChangePassword: 'Failed to change password',
    emailPasswordRequired: 'Email and password are required',
    userCreated: 'User created successfully',
    failedToCreateUser: 'Failed to create user',
    userDeleted: 'User deleted successfully',
    failedToDeleteUser: 'Failed to delete user',
    failedToStartCheckout: 'Failed to start checkout',
    failedToOpenBillingPortal: 'Failed to open billing portal',
    failedToLoadSettings: 'Failed to load settings',
    loadingSettings: 'Loading settings...',
    confirmDeleteUser: 'Are you sure you want to delete this user?',

    // Page headers
    manageSettings: 'Manage your company and account settings',

    // Language
    language: 'Language',
    german: 'Deutsch',
    english: 'English',

    // Dashboard
    afterHoursOverview: 'After-Hours Service Overview',
    dark: 'Dark',
    light: 'Light',
    callsTonight: 'Calls Tonight',
    openIncidents: 'Open Incidents',
    activePMs: 'Active PMs',
    totalProperties: 'Total Properties',
    totalActiveCompanies: 'Total active companies',
    acrossAllPMs: 'Across all PMs',
    callsToday: 'Calls Today',
    requiresAttention: 'Requires attention',
    allClear: 'All clear',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    emergencies: 'Emergencies',
    missingReports: 'Missing Reports',
    calls: 'calls',
    callActivityLast7Days: 'Call Activity (Last 7 Days)',
    resolved: 'Resolved',
    responseRate: 'Response Rate',
    completed: 'Completed',
    avgResponse: 'avg response',
    manageCompanies: 'Manage Companies',
    servicePhone: 'Service Phone',
    lastIncident: 'Last Incident',
    action: 'Action',
    enter: 'Enter',
    noPmCompaniesYet: 'No PM Companies Yet',
    addFirstPmCompanyDescription: 'Start by adding your first PM company to manage their properties and tenants.',
    addPmCompany: 'Add PM Company',
    gettingStarted: 'Getting Started',
    gettingStartedDescription: 'Select a PM Company from the table above to enter its workspace. Inside a PM workspace, you can manage properties, tenants, service providers, and view PM-specific incidents and reports.',
    loadingDashboard: 'Loading dashboard...',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',

    // Onboarding Checklist
    completeYourSetup: 'Complete Your Setup',
    stepsCompleted: '{0} of {1} steps completed',
    tour: 'Tour',
    dismissChecklist: 'Dismiss checklist',
    done: 'Done',
    onboardingWelcomeTitle: 'Welcome to After Hour Dispatch',
    onboardingWelcomeDesc: "Let's get you set up",
    onboardingAddPmTitle: 'Add Your First Client',
    onboardingAddPmDesc: 'Add a Property Management company you serve',
    onboardingAddSpTitle: 'Add Service Providers',
    onboardingAddSpDesc: 'Add contractors (plumbers, electricians, etc.)',
    onboardingAddEmployeeTitle: 'Add Team Members',
    onboardingAddEmployeeDesc: 'Add employees who can be on-call',
    onboardingScheduleTitle: 'Set Up On-Call Schedule',
    onboardingScheduleDesc: 'Configure who handles after-hours calls',
    onboardingEmergencyLineTitle: 'Set up your emergency line',
    onboardingEmergencyLineDesc: 'Get a number or forward your existing one — takes 2 minutes',

    // Emergency Line (Telephony)
    emergencyLine: 'Emergency Line',
    emergencyLineIntro: 'The phone number your tenants call for after-hours emergencies. Set one up per client.',
    emergencyLineNotSetUp: "Your emergency line isn't set up yet.",
    emergencyLineNotSetUpDesc: 'Tenants cannot reach After Hour until you finish this.',
    finishSetup: 'Finish setup',
    getDedicatedNumber: 'Get a dedicated number',
    useMyOwnNumber: 'Use my own number (free)',
    yourEmergencyNumber: 'Your emergency number',
    yourPublishedNumber: 'The number your tenants currently call',
    yourNumber: 'Your number',
    enterYourNumber: 'Enter your published number first',
    forwardsTo: 'Forwards to',
    forwardYourLineTo: 'Set conditional call-forwarding (on no-answer) from your published number to',
    carrierInstructions: 'Per-carrier instructions',
    perMonth: 'month',
    lineIsLive: 'Your emergency line is live.',
    testMyLine: 'Test my line',
    iHeardIt: 'I heard the assistant',
    checkNumberConfig: 'Number configured',
    checkRouting: 'Routing verified',
    releaseThisNumber: 'Release this number',
    confirmReleaseNumber: 'Release this number? Tenants will no longer be able to reach After Hour on it.',
    provisioningUnavailable: 'Number setup is temporarily unavailable — contact support.',
    addClientFirst: 'Add a client (PM company) first, then set up its emergency line here.',
    lineStatusActive: 'Active',
    lineStatusProvisioning: 'Setting up',
    lineStatusForwardingPending: 'Forwarding setup pending',
    lineStatusPortPending: 'Port pending',
    lineStatusUnassigned: 'Not set up',
    lineStatusReleased: 'Released',

    // Welcome Modal
    welcomeModalTitle: 'Welcome to After Hour Dispatch!',
    welcomeModalSubtitle: 'Your after-hours emergency dispatch system is ready',
    welcomeModalBody: "Let's get your account set up so you can start managing after-hours emergencies for your clients.",
    takeQuickTour: 'Take a Quick Tour',
    skipTourShowChecklist: 'Skip Tour, Show Me the Checklist',
    whatYoullSetUp: "What you'll set up:",
    welcomeSetupPm: 'Add PM companies (your clients)',
    welcomeSetupSp: 'Add service providers (plumbers, electricians)',
    welcomeSetupTeam: 'Set up your team members',
    welcomeSetupSchedule: 'Configure on-call schedules',

    // Guided Tour
    tourSidebarTitle: 'Navigation',
    tourSidebarContent: 'Use the sidebar to navigate between sections. Dashboard shows your overview, and you can manage PM Companies, Service Providers, and more.',
    tourPmCompaniesTitle: 'PM Companies',
    tourPmCompaniesContent: 'Start here! Add the Property Management companies you provide after-hours service for.',
    tourServiceProvidersTitle: 'Service Providers',
    tourServiceProvidersContent: 'Add your contractors - plumbers, electricians, locksmiths - who handle emergency calls.',
    tourEmployeesTitle: 'Your Team',
    tourEmployeesContent: 'Add your team members who can be assigned to on-call shifts.',
    tourSchedulesTitle: 'On-Call Schedules',
    tourSchedulesContent: 'Set up who handles calls during after-hours. You can create recurring schedules or one-time assignments.',
    tourIncidentsTitle: 'Incidents',
    tourIncidentsContent: "All incoming calls and emergencies appear here. You'll see real-time updates as calls come in.",
    tourStepOf: 'Step {0} of {1}',
    tourFinish: 'Finish',
    tourNext: 'Next',
    tourPrevious: 'Previous',
    tourSkip: 'Skip tour',

    // Login/Signup
    fmAdminPortal: 'FM Admin Portal',
    emailAddress: 'Email address',
    enterYourEmail: 'Enter your email',
    enterYourPassword: 'Enter your password',
    forgotPassword: 'Forgot password?',
    signingIn: 'Signing in...',
    signIn: 'Sign in',
    dontHaveAccount: "Don't have an account?",
    startFreeTrial: 'Start free trial',
    afterHoursEmergencyDispatch: 'After-hours emergency dispatch system',
    loginFailed: 'Login failed',

    // Signup
    startYourFreeTrial: 'Start Your Free Trial',
    companyNameRequired: 'Company name is required',
    companyPhoneRequired: 'Company phone number is required',
    yourNameRequired: 'Your name is required',
    emailRequired: 'Email is required',
    invalidEmail: 'Please enter a valid email address',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 8 characters',
    passwordsMustMatch: 'Passwords do not match',
    yourFmCompanyName: 'Your FM Company Name',
    companyPhoneNumber: 'Company Phone Number',
    mainCompanyContact: 'Your main company contact number',
    onCallPhoneOptional: 'On-Call Phone (Optional)',
    escalationPhoneNumber: 'Escalation phone number',
    whereUrgentEscalations: 'Where urgent escalations are sent (defaults to company phone)',
    continue: 'Continue',
    alreadyHaveAccount: 'Already have an account?',
    yourFullName: 'Your Full Name',
    atLeast8Characters: 'At least 8 characters',
    confirmYourPassword: 'Confirm your password',
    freeTrialDays: '14-Day Free Trial',
    noCreditCardRequired: 'No credit card required. Full access to all features.',
    back: 'Back',
    creatingAccount: 'Creating account...',
    createAccount: 'Create Account',
    agreeToTerms: 'By creating an account, you agree to our Terms of Service and Privacy Policy',
    agreeToTermsCheckbox: 'I agree to the',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    mustAcceptTerms: 'You must accept the Terms of Service to continue',
    account: 'Account',
    verify: 'Verify',
    weWillSendCode: "We'll send you a verification code",
    sendCode: 'Send Code',
    verifyCode: 'Verify Code',
    verifying: 'Verifying...',
    codeSentTo: 'Code sent to',
    didntReceiveCode: "Didn't receive the code?",
    resendIn: 'Resend in',
    resendCode: 'Resend code',
    changeEmail: 'Change email',

    // Status Banners
    trialExpired: 'Your trial has expired.',
    daysLeftTrial: 'days left in your free trial.',
    dayLeftTrial: 'day left in your free trial.',
    subscribeNowToContinue: 'Subscribe now to continue using After Hour Dispatch.',
    upgradeToKeepData: 'Upgrade to keep your data and continue after the trial.',
    subscribeNow: 'Subscribe Now',
    upgrade: 'Upgrade',
    verifyEmailAddress: 'Please verify your email address',
    toReceiveNotifications: 'to ensure you receive important notifications.',
    verificationEmailSent: 'Verification email sent!',
    sending: 'Sending...',
    resendEmail: 'Resend Email',
    dismiss: 'Dismiss',

    // Buildings Page
    loadingBuildings: 'Loading buildings...',
    managePropertiesAcrossPM: 'Manage properties across all PM companies',
    totalBuildings: 'Total Buildings',
    totalTenants: 'Total Tenants',
    buildingsByPmCompany: 'Buildings by PM Company',
    selectCompanyToManage: 'Select a company to manage its buildings',
    noPmCompaniesYetBuildings: 'No PM Companies Yet',
    addFirstPmToManageBuildings: 'Add your first PM company to start managing buildings.',

    // Tenants Page
    loadingTenants: 'Loading tenants...',
    manageTenantsAcrossPM: 'Manage tenants across all PM companies',
    tenantsByPmCompany: 'Tenants by PM Company',
    selectCompanyToManageTenants: 'Select a company to manage its tenants',
    addFirstPmToManageTenants: 'Add your first PM company to start managing tenants.',

    // Service Providers Page
    loadingServiceProviders: 'Loading service providers...',
    contractorsAndVendors: 'Contractors and vendors for emergency repairs',
    totalProviders: 'Total Providers',
    paused: 'Paused',
    allPmCompanies: 'All PM Companies',
    allTrades: 'All Trades',
    addProvider: 'Add Provider',
    noServiceProviders: 'No Service Providers',
    addContractorsDescription: 'Add contractors and vendors to dispatch for emergency repairs.',
    trade: 'Trade',
    phone: 'Phone',
    editServiceProvider: 'Edit Service Provider',
    addServiceProvider: 'Add Service Provider',
    editing: 'Editing:',
    addContractorOrVendor: 'Add a contractor or vendor',
    companyInformationSection: 'Company Information',
    tradeSpecialty: 'Trade / Specialty',
    contactInformation: 'Contact Information',
    contactPerson: 'Contact Person',
    primaryContactName: 'Primary contact name',
    availabilityGuidanceSection: 'Availability & Guidance',
    usageNote: 'Note for on-call staff',
    usageNoteHint: 'e.g. "24/7 emergency line, ~30min arrival" or "Business hours only, use as backup"',
    available24h: 'Available 24/7',
    availableHoursOnly: 'Only available during specific hours',
    availableFrom: 'Available from',
    availableTo: 'Available until',
    plumber: 'Plumber',
    electrician: 'Electrician',
    locksmith: 'Locksmith',
    hvac: 'HVAC',
    general: 'General',
    other: 'Other',
    savingChanges: 'Saving...',

    // PM Companies Page
    loadingPmCompanies: 'Loading PM companies...',
    pmCompaniesDescription: 'Property management companies you serve with after-hours dispatch',
    totalCompanies: 'Total Companies',
    withServicePhone: 'With Service Phone',
    searchPlaceholder: 'Search by name, email, or service phone...',
    allCompanies: 'All Companies',
    activeOnly: 'Active Only',
    inactiveOnly: 'Inactive Only',
    withOpenIncidents: 'With Open Incidents',
    noOpenIncidents: 'No Open Incidents',
    showingXofY: 'Showing {0} of {1} companies',
    afterHours: 'After Hours',
    notSet: 'Not set',
    noResultsFound: 'No Results Found',
    tryAdjustingSearch: 'Try adjusting your search or filter criteria.',
    editPmCompany: 'Edit PM Company',
    addNewPmCompany: 'Add a new property management company',
    servicePhoneHotline: 'Service Phone (After-Hours Hotline)',
    tenantsCallThis: 'Tenants call this number',
    address: 'Address',
    streetAddress: 'Street address',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    emailForReports: 'For reports',
    phoneForEscalations: 'For escalations',
    afterHoursSettings: 'After-Hours Settings',
    afterHoursStart: 'After-Hours Start',
    afterHoursEnd: 'After-Hours End',
    aiDecisionsBelowThreshold: 'AI decisions below this threshold require human review',
    additionalNotes: 'Additional Notes',
    internalNotes: 'Internal notes about this PM company...',
    createCompany: 'Create Company',
    confirmDeletePm: 'Delete "{0}"? This will fail if there are buildings assigned.',
    edit: 'Edit',
    delete: 'Delete',

    // Employees Page
    employeesAndOnCall: 'Employees & On-Call',
    manageTeamAndRotations: 'Manage your team and plan on-call rotations in advance',
    addEmployee: 'Add Employee',
    currentlyOnCall: 'CURRENTLY ON-CALL',
    callsForwarded: 'Calls Forwarded',
    shiftHours: 'Shift Hours',
    totalEmployees: 'Total Employees',
    onCallReady: 'On-Call Ready',
    weeksPlanned: 'Weeks Planned',
    weeklyRotation: 'Weekly Rotation',
    teamMembersTab: 'Team Members',
    callForwardingStatus: 'Call Forwarding Status',
    forwardingTo: 'Active - Forwarding to',
    noActiveOnCall: 'No active on-call assignment',
    configure: 'Configure',
    setUp: 'Set Up',
    previous: 'Previous',
    next: 'Next',
    today: 'Today',
    past: 'Past',
    week: 'Week',
    physicalPhone: 'PHYSICAL PHONE',
    notAssigned: 'Not Assigned',
    pastWeek: 'Past week',
    clickToAssign: 'Click to assign an employee',
    change: 'Change',
    assign: 'Assign',
    noOnCallEmployees: 'No On-Call Employees',
    addEmployeesOnCallDescription: 'Add employees and mark them as "Can Be On-Call" to start scheduling rotations.',
    addFirstEmployee: 'Add First Employee',
    searchEmployees: 'Search employees...',
    onCall: 'ON-CALL',
    dispatcher: 'Dispatcher',
    noEmployeesYet: 'No Employees Yet',
    addTeamMembersDescription: 'Add your team members to manage on-call rotations.',
    editEmployee: 'Edit Employee',
    addNewEmployee: 'Add New Employee',
    updateEmployeeInfo: 'Update employee information',
    addTeamMemberToSystem: 'Add a team member to the system',
    basicInformation: 'Basic Information',
    enterFullName: 'Enter full name',
    phoneNumber: 'Phone Number',
    optional: 'Optional',
    settingsSection: 'Settings',
    activeEmployee: 'Active Employee',
    canLoginAndAssigned: 'Employee can log in and be assigned tasks',
    availableForOnCall: 'Available for On-Call',
    canBeAssignedRotations: 'Can be assigned to weekly on-call rotations',
    notes: 'Notes',
    internalNotesEmployee: 'Internal notes about this employee...',
    confirmDeleteEmployee: 'Delete employee "{0}"? This will also remove their on-call assignments.',
    nameAndPhoneRequired: 'Name and phone are required',
    failedToSaveEmployee: 'Failed to save employee:',
    failedToDeleteEmployee: 'Failed to delete employee:',
    assignOnCallWeek: 'Assign On-Call Week',
    currentWeek: 'Current Week',
    selectEmployee: 'Select Employee',
    noEmployeesForOnCall: 'No employees available for on-call duty.',
    noAssignment: 'No Assignment',
    clearWeekOnCall: "Clear this week's on-call",
    phoneHandling: 'Phone Handling',
    usePhysicalPhone: 'Use Physical Phone',
    employeeCarriesPhone: 'Employee will carry the physical after-hours phone this week',
    callForwardingInfo: 'Call Forwarding: Calls will be automatically forwarded to the employee\'s personal phone number.',
    notesOptional: 'Notes (Optional)',
    specialInstructionsWeek: 'Any special instructions for this week...',
    immediateEffect: 'Immediate Effect',
    changeWillTakeEffect: 'This change will take effect immediately and update call forwarding.',
    saveAssignment: 'Save Assignment',
    failedToSaveAssignment: 'Failed to save assignment:',

    // Incidents Page
    pmScopedView: 'PM-SCOPED VIEW',
    fmGlobalView: 'FM GLOBAL VIEW',
    incidentsFor: 'Incidents:',
    allIncidentsAcrossPM: 'All Incidents Across PM Companies',
    allIncidents: 'All incidents',
    openOnly: 'Open only',
    emergenciesOnly: 'Emergencies only',
    clearPmFilter: 'Clear PM filter',
    dateTime: 'Date/Time',
    building: 'Building',
    issue: 'Issue',
    severity: 'Severity',
    aiConf: 'AI Conf.',
    responsibility: 'Responsibility',
    assignedSp: 'Assigned SP',
    noIncidentsFound: 'No incidents found',
    emergency: 'EMERGENCY',
    normal: 'Normal',
    reportOverdue: 'Report overdue',
    spWorking: 'SP working',
    awaitingSp: 'Awaiting SP',
    fmEscalated: 'FM escalated',

    // Reports Page
    reportsTitle: 'Reports',
    pmCompanyColumn: 'PM Company',
    incidentsCount: 'Incidents',
    sentTo: 'Sent to',
    statusColumn: 'Status',
    actionsColumn: 'Actions',
    noReportsYet: 'No reports yet',
    sent: 'Sent',
    pending: 'Pending',
    viewPdf: 'View PDF',
    resend: 'Resend',
    enterEmailToSend: 'Enter email address to send report to:',
    reportSentSuccessfully: 'Report sent successfully',

    // Forgot Password Page
    resetYourPassword: 'Reset Your Password',
    enterEmailForReset: 'Enter your email address and we\'ll send you a link to reset your password.',
    pleaseEnterEmail: 'Please enter your email address',
    sendResetLink: 'Send Reset Link',
    checkYourEmail: 'Check Your Email',
    ifAccountExists: 'If an account exists for {0}, you\'ll receive a password reset link shortly.',
    didntReceiveEmail: 'Didn\'t receive the email? Check your spam folder or try again.',
    tryAnotherEmail: 'Try another email',
    backToSignIn: 'Back to Sign In',

    // Reset Password Page
    setNewPassword: 'Set New Password',
    creatingPasswordFor: 'Creating new password for',
    pleaseEnterNewPassword: 'Please enter a new password',
    passwordMust8Chars: 'Password must be at least 8 characters',
    passwordsDoNotMatchReset: 'Passwords do not match',
    verifyingResetLink: 'Verifying reset link...',
    invalidResetLink: 'Invalid Reset Link',
    resetLinksExpire: 'Reset links expire after 1 hour. Please request a new one.',
    requestNewLink: 'Request New Link',
    passwordResetComplete: 'Password Reset Complete',
    passwordResetSuccess: 'Your password has been successfully reset. You can now sign in with your new password.',
    confirmNewPassword: 'Confirm New Password',
    resetting: 'Resetting...',
    resetPassword: 'Reset Password',

    // Verify Email Page
    verifyingEmail: 'Verifying your email...',
    verificationFailed: 'Verification Failed',
    verificationLinksExpire: 'Verification links expire after 24 hours.',
    goToDashboard: 'Go to Dashboard',
    emailVerified: 'Email Verified!',
    emailVerifiedSuccess: 'Your email has been successfully verified. You now have full access to all features.',
    noVerificationToken: 'No verification token provided',
    pageNotFound: 'We could not find that page.',
    backToDashboard: 'Back to dashboard',
    cookieTitle: 'We use cookies',
    cookieBody: 'We use cookies to improve your experience, analyze site traffic, and for security. By clicking "Accept All", you consent to our use of cookies. You can customize your preferences or reject non-essential cookies.',
    cookieRejectAll: 'Reject All',
    cookieCustomize: 'Customize',
    cookieAcceptAll: 'Accept All',
    cookiePreferences: 'Cookie Preferences',
    cookieEssentialTitle: 'Essential Cookies',
    cookieEssentialDesc: 'Required for the website to function. Cannot be disabled.',
    cookieAnalyticsTitle: 'Analytics Cookies',
    cookieAnalyticsDesc: 'Help us understand how visitors interact with our website.',
    cookieFunctionalTitle: 'Functional Cookies',
    cookieFunctionalDesc: 'Enable personalized features and remember your preferences.',
    cookieSavePreferences: 'Save Preferences',
    cookiePrivacyPolicy: 'Privacy Policy',
  }
};

const LanguageContext = createContext(null);

/**
 * Detect browser/OS language
 */
function detectLanguage() {
  // Check localStorage first
  const saved = localStorage.getItem('preferred_language');
  if (saved && (saved === 'de' || saved === 'en')) {
    return saved;
  }

  // Detect from browser/OS. Previously only ever confirmed German and fell
  // through to the German default for every other language, including
  // English — meaning an English browser could never actually be detected
  // as English. Now actually branches on what the browser reports.
  const browserLang = navigator.language || navigator.userLanguage;
  if (browserLang) {
    const lang = browserLang.split('-')[0].toLowerCase();
    if (lang === 'de') return 'de';
    if (lang === 'en') return 'en';
  }

  // Only reached when the browser reports neither de nor en (or reports
  // nothing) — default to German since target market is German.
  return 'de';
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => detectLanguage());

  // Keep <html lang> in sync with the language actually being rendered.
  // It was hardcoded "en" in index.html, so German pages advertised
  // themselves as English to screen readers, browser translation prompts
  // and search engines (QA 2026-08-09).
  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('preferred_language', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  // Get all translations for current language
  const translations_current = translations[language] || translations.en;

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      t,
      translations: translations_current,
      availableLanguages: ['de', 'en']
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
