/**
 * Shared style object for the on-call cockpit. Kept as an inline-style object
 * (this app has no Tailwind) and centralised here so the Flutter port has one
 * styling reference. Dark by default, ≥44px tap targets, one-handed at 3am.
 */
export const s = {
  shell: {
    minHeight: '100vh',
    background: '#0f172a',
    color: '#f1f5f9',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    padding: '16px',
    maxWidth: '600px',
    margin: '0 auto',
  },
  centered: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '80vh',
    fontSize: '18px',
    textAlign: 'center',
    padding: '24px',
  },
  errorText: { color: '#f87171' },

  // Zone 1 — verdict
  badge: {
    padding: '12px 16px',
    borderRadius: '8px',
    fontWeight: 800,
    fontSize: '18px',
    textAlign: 'center',
    letterSpacing: '0.02em',
    color: '#fff',
  },
  verdictLine: {
    fontSize: '19px',
    fontWeight: 700,
    lineHeight: 1.3,
    margin: '14px 0 10px',
  },
  recommendBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: '8px',
    padding: '12px 14px',
    fontSize: '15px',
    fontWeight: 600,
  },
  recommendIcon: { fontSize: '20px', flexShrink: 0 },

  countdown: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    marginTop: '12px',
    padding: '10px 12px',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 600,
    background: '#1e293b',
    border: '1px solid #334155',
  },
  countdownUrgent: {
    background: '#450a0a',
    border: '1px solid #b91c1c',
    color: '#fecaca',
  },
  countdownExplain: { fontSize: '12px', color: '#94a3b8', marginTop: '6px', textAlign: 'center' },

  // sections
  section: {
    background: '#1e293b',
    borderRadius: '12px',
    padding: '16px',
    marginTop: '12px',
  },
  sectionTitle: {
    fontSize: '13px',
    textTransform: 'uppercase',
    color: '#94a3b8',
    margin: '0 0 12px 0',
    letterSpacing: '0.06em',
  },
  sectionSubtitle: { fontSize: '14px', color: '#cbd5e1', margin: '12px 0 8px' },

  // Zone 2 — assessment
  assessUnsure: {
    background: '#3b0764',
    border: '1px solid #7e22ce',
    borderRadius: '8px',
    padding: '12px 14px',
    fontSize: '15px',
    color: '#f3e8ff',
  },
  assessYes: {
    background: '#450a0a',
    border: '1px solid #b91c1c',
    borderRadius: '8px',
    padding: '12px 14px',
    fontSize: '15px',
    color: '#fee2e2',
  },
  assessNo: {
    background: '#052e16',
    border: '1px solid #15803d',
    borderRadius: '8px',
    padding: '12px 14px',
    fontSize: '15px',
    color: '#dcfce7',
  },
  assessStrong: { fontWeight: 700, display: 'block', marginBottom: '4px' },
  assessReason: { fontSize: '13px', opacity: 0.9, margin: '6px 0 0', lineHeight: 1.45 },
  confNote: { fontSize: '12px', color: '#94a3b8', margin: '8px 0 0' },

  reportedText: { fontSize: '16px', lineHeight: 1.5, margin: '4px 0 0' },

  unusualList: { display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '4px' },
  unusualItem: {
    display: 'flex',
    gap: '8px',
    alignItems: 'flex-start',
    fontSize: '14px',
    background: '#0f172a',
    borderRadius: '6px',
    padding: '10px 12px',
    lineHeight: 1.4,
  },

  // verification badge
  vbadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    fontWeight: 600,
    padding: '5px 10px',
    borderRadius: '999px',
  },
  vbadgeOk: { background: '#052e16', color: '#86efac', border: '1px solid #15803d' },
  vbadgeWarn: { background: '#422006', color: '#fdba74', border: '1px solid #b45309' },

  // Zone 3 — detail
  detailToggle: {
    width: '100%',
    background: '#1e293b',
    border: '1px solid #334155',
    color: '#93c5fd',
    fontSize: '15px',
    fontWeight: 600,
    padding: '14px',
    borderRadius: '10px',
    marginTop: '12px',
    cursor: 'pointer',
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    padding: '7px 0',
    borderBottom: '1px solid #334155',
    fontSize: '15px',
  },
  rowLabel: { color: '#94a3b8', flexShrink: 0 },
  rowValue: { fontWeight: 600, textAlign: 'right' },
  qaList: { display: 'flex', flexDirection: 'column', gap: '6px', margin: '4px 0' },
  qaItem: { display: 'flex', flexDirection: 'column', background: '#0f172a', borderRadius: '6px', padding: '8px 10px' },
  qaQ: { fontSize: '13px', color: '#94a3b8' },
  qaA: { fontSize: '15px', fontWeight: 600, marginTop: '2px' },
  transcript: {
    whiteSpace: 'pre-wrap',
    fontSize: '13px',
    color: '#cbd5e1',
    background: '#0f172a',
    borderRadius: '6px',
    padding: '10px 12px',
    marginTop: '6px',
    maxHeight: '320px',
    overflowY: 'auto',
    lineHeight: 1.5,
  },
  callButton: {
    display: 'block',
    background: '#334155',
    color: '#fff',
    textDecoration: 'none',
    padding: '14px',
    borderRadius: '8px',
    textAlign: 'center',
    fontSize: '16px',
    fontWeight: 600,
    margin: '12px 0',
  },
  secondaryLink: { display: 'block', color: '#60a5fa', textDecoration: 'none', marginTop: '10px', fontSize: '15px' },
  accessGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px', marginTop: '8px' },
  accessItem: { background: '#0f172a', padding: '8px 10px', borderRadius: '6px' },
  accessLabel: { display: 'block', fontSize: '11px', color: '#94a3b8', textTransform: 'uppercase' },
  accessValue: { fontSize: '15px', fontWeight: 600 },
  note: { fontSize: '14px', color: '#fbbf24', marginTop: '10px', lineHeight: 1.4 },
  forwardWarning: {
    fontSize: '13px',
    color: '#fca5a5',
    background: '#450a0a',
    border: '1px solid #7f1d1d',
    borderRadius: '6px',
    padding: '8px 10px',
    marginTop: '10px',
  },

  // Zone 4 — decide
  decisionButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    width: '100%',
    border: 'none',
    color: '#fff',
    fontSize: '17px',
    fontWeight: 700,
    padding: '18px',
    borderRadius: '10px',
    marginTop: '10px',
    cursor: 'pointer',
    textAlign: 'left',
  },
  decisionButtonSecondary: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    width: '100%',
    background: '#1e293b',
    border: '1px solid #334155',
    color: '#e2e8f0',
    fontSize: '16px',
    fontWeight: 600,
    padding: '16px',
    borderRadius: '10px',
    marginTop: '10px',
    cursor: 'pointer',
    textAlign: 'left',
  },
  btnIcon: { fontSize: '20px', flexShrink: 0 },
  divider: { border: 0, borderTop: '1px solid #334155', margin: '18px 0 4px' },
  dividerLabel: { fontSize: '12px', color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.06em', marginTop: '14px' },

  select: {
    width: '100%',
    background: '#0f172a',
    color: '#f1f5f9',
    border: '1px solid #334155',
    borderRadius: '8px',
    padding: '12px',
    fontSize: '15px',
    marginTop: '6px',
  },
  textarea: {
    width: '100%',
    minHeight: '64px',
    background: '#0f172a',
    color: '#f1f5f9',
    border: '1px solid #334155',
    borderRadius: '8px',
    padding: '10px',
    fontSize: '14px',
    marginTop: '8px',
    boxSizing: 'border-box',
  },

  // SP picker
  spOption: {
    display: 'flex',
    gap: '10px',
    alignItems: 'flex-start',
    background: '#0f172a',
    border: '1px solid #334155',
    borderRadius: '8px',
    padding: '12px',
    marginTop: '8px',
    cursor: 'pointer',
  },
  spOptionSelected: { borderColor: '#3b82f6', background: '#172554' },
  spRadio: { marginTop: '3px', flexShrink: 0, width: '18px', height: '18px' },
  spName: { fontSize: '16px', fontWeight: 700 },
  spMeta: { fontSize: '13px', color: '#94a3b8', marginTop: '3px', display: 'flex', flexWrap: 'wrap', gap: '6px 10px' },
  spNote: { fontSize: '13px', color: '#cbd5e1', marginTop: '5px', fontStyle: 'italic' },
  pill: { fontSize: '11px', fontWeight: 700, padding: '2px 8px', borderRadius: '999px', whiteSpace: 'nowrap' },
  pillOpen: { background: '#052e16', color: '#86efac' },
  pillClosed: { background: '#422006', color: '#fdba74' },
  pill247: { background: '#1e3a8a', color: '#bfdbfe' },
  pillSuggested: { background: '#3b0764', color: '#e9d5ff' },
  pillRank: { background: '#334155', color: '#cbd5e1' },

  // confirm sheet
  confirmSheet: {
    position: 'fixed',
    left: 0,
    right: 0,
    bottom: 0,
    background: '#1e293b',
    borderTop: '1px solid #475569',
    borderTopLeftRadius: '16px',
    borderTopRightRadius: '16px',
    padding: '20px 16px calc(20px + env(safe-area-inset-bottom))',
    maxWidth: '600px',
    margin: '0 auto',
    zIndex: 50,
    boxShadow: '0 -8px 32px rgba(0,0,0,0.5)',
  },
  confirmBackdrop: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.5)',
    zIndex: 49,
  },
  confirmTitle: { fontSize: '18px', fontWeight: 700, marginBottom: '6px' },
  confirmBody: { fontSize: '14px', color: '#cbd5e1', marginBottom: '16px', lineHeight: 1.45 },

  // holding / info banners
  infoBanner: {
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: '8px',
    padding: '12px 14px',
    fontSize: '14px',
    marginTop: '12px',
    lineHeight: 1.45,
  },
  warnBanner: {
    background: '#422006',
    border: '1px solid #b45309',
    borderRadius: '8px',
    padding: '12px 14px',
    fontSize: '14px',
    color: '#fed7aa',
    marginTop: '10px',
    lineHeight: 1.45,
  },

  copyBox: {
    display: 'flex',
    gap: '8px',
    marginTop: '8px',
  },
  copyInput: {
    flex: 1,
    background: '#0f172a',
    color: '#93c5fd',
    border: '1px solid #334155',
    borderRadius: '8px',
    padding: '10px',
    fontSize: '13px',
    minWidth: 0,
  },
  copyBtn: {
    background: '#2563eb',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 14px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
};

export const URGENCY_COLOR = {
  critical: '#ef4444',
  urgent: '#f97316',
  unclear: '#a855f7',
  low: '#22c55e',
};
